# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: Web
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: FlutterInstall@0
        inputs:
          mode: 'auto'
          channel: 'stable'
          version: 'latest'

      - task: FlutterBuild@0
        inputs:
          target: 'web'
          projectDirectory: '.'
          entryPoint: 'lib/main.dart'

      #- task: FlutterTest@0
      #  inputs:
      #    projectDirectory: '.'

      - task: CopyFiles@2
        displayName: 'Copy Files'
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/build/web'
          TargetFolder: '$(Build.ArtifactStagingDirectory)'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'ci-artifacts'
          publishLocation: 'Container'