trigger:
  branches:
    include:
    - master

pool:  
  vmImage: 'ubuntu-latest'  
resources:
  repositories:
  - repository: templates
    type: git
    name: Pipelines-Templates/Pipelines-Templates

steps:
- template: 'pipeline-templates/flutter/v3/build-and-publish-web.yml@templates'
  parameters:
    buildConfiguration: '$(Build.SourceBranchName)'
    tags: '$(Build.BuildId)'
    imageRepository: '$(Build.SourceBranchName)/web/timey'
    containerRegistry: 'Zero8-Container-Registry'