apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: timey-web-ingress
  namespace: zero8
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
    - timey.zero8.io
    secretName: tls-secret
  rules:
  - host: timey.zero8.io
    http:
      paths:
      - backend:
          service:
            name: timey-web
            port:
              number: 80
        path: /
        pathType: Prefix